version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: url-shortener
    ports:
      - "5000:5000"
    depends_on:
      - redis
